spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration


  data:
    redis:
      host: localhost
      port: 6379
    mongodb:
      uri: mongodb://root:123@localhost:27017/learning_english?authSource=admin
      database: learning_english

jwt:
  signer-key: "bTjB9aNwmnrGaTjQEBciTlZlC6iYu3q8uqOCQbIX25FSgkDBLnQ+m6yMZOX1VqJU"
  access:
    expiration: "3600" #in second
  refresh:
    expiration: "12000" #in second