spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect


  data:
    redis:
      host: localhost
      port: 6379
    mongodb:
      uri: mongodb://root:123@localhost:27017/learning_english?authSource=admin
      database: learning_english
